name: ArmorStandGUI
version: '${project.version}'
main: mc.gregvroberts.armorstandgui.ArmorStandGUI
api-version: 1.17
authors: [ gregvroberts ]
description: A Spigot 1.17.1 Armor Stand GUI Plugin
website: github.com/gregvroberts/ArmorStandGUI
